#!/bin/sh

# This script checks whether the CSS can be generated by the Ruby Sass
# gem. If you're using libsass, this is a good way to check whether the
# stylesheets can also be generated in Ruby projects.

check_dependencies()
{
    which sass >/dev/null
    if [ $? -ne 0 ]; then
        echo "Please install the sass Ruby gem, and try again" 1>&2
        exit 1
    fi
}

check_compatibility()
{
    sass -Istyles styles/_coop-toolkit.scss > /dev/null

    if [ $? -eq 0 ]; then
        echo "PASS"
    else
        echo "FAIL"
        exit 1
    fi
}

check_dependencies
check_compatibility
